const TOURS = [
  {
    id: 'villajoyosa-chocolate',
    name: 'Villajoyosa: Sweet Temptations',
    tagline: "Spain's oldest chocolate traditions",
    shortDesc: "Explore vibrant coastal beauty and dive into Spain's oldest chocolate traditions on an exclusive full-day journey.",
    duration: 'Full day · 6–7 hrs',
    price: '€189',
    priceNum: 189,
    maxGuests: 4,
    transport: 'Private Car',
    category: 'Culinary & Culture',
    image: 'https://horizons-cdn.hostinger.com/fdaae8f6-c2cb-4e61-863e-e79e6b571eca/45fb6619bb798d20fa0d7374cc82fc50.png',
    highlights: ['Factory tour', 'Pro tasting', 'Gourmet lunch', 'Chocolate workshop'],
    fullDesc: "Step into a world where the air is thick with the intoxicating aroma of roasted cocoa. Villajoyosa, with its iconic brightly painted fishermen's houses, is the historic heart of Spain's chocolate-making tradition. This exclusive journey blends centuries-old heritage with modern culinary excellence.\n\nYou'll tour an exclusive historic chocolate factory, watch master artisans at work, then sit down for a guided sensory tasting session. A multi-course gourmet lunch featuring regional specialties follows, then a hands-on workshop where you craft your own personalized chocolate creation under the guidance of a master chocolatier.",
    featured: true
  },
  {
    id: 'sierra-nevada',
    name: 'Sierra Nevada: Alpine Winter Escape',
    tagline: "Spain's highest mountain ski adventure",
    shortDesc: "Experience the thrill of winter sports in Spain's highest mountains with an exclusive, all-inclusive ski adventure.",
    duration: '2 or 3 Days',
    price: 'From €800',
    priceNum: 800,
    maxGuests: 4,
    transport: 'Private Car',
    category: 'Adventure & Sports',
    image: 'https://horizons-cdn.hostinger.com/fdaae8f6-c2cb-4e61-863e-e79e6b571eca/9ad7a02375695d15c9f267db0389f43c.png',
    highlights: ['VIP equipment fitting', 'Guided orientation', 'Alpine lunch', 'Après-ski'],
    fullDesc: "Leave the Mediterranean coast behind and ascend into the breathtaking, snow-capped peaks of the Sierra Nevada. Spain's premier winter destination, this majestic mountain range offers pristine slopes, brilliant sunshine, and an unparalleled alpine atmosphere.\n\nChoose the 2-day (€800) or 3-day (€1,100) package. We handle every logistical detail — transport, hotel accommodation, VIP equipment fitting, guided mountain orientation and alpine lunches. The 3-day option includes our exclusive après-ski relaxation evening with premium drinks and tapas.",
    featured: true
  },
  {
    id: 'juan-gil-wine',
    name: 'Juan Gil: The Art of Jumilla Wine',
    tagline: 'Elite winemaking in sun-drenched vineyards',
    shortDesc: "A sophisticated journey through Spain's celebrated wine heritage in the vineyards of Jumilla.",
    duration: 'Full day · 7–8 hrs',
    price: '€225',
    priceNum: 225,
    maxGuests: 4,
    transport: 'Private Car',
    category: 'Wine & Gastronomy',
    image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&q=80&w=1200',
    highlights: ['VIP vineyard access', 'Sommelier tasting', 'Gourmet pairing lunch', 'Cellar access'],
    fullDesc: "Step into the world of Juan Gil, where centuries of winemaking tradition meet modern excellence. The arid, sun-drenched landscapes of Jumilla produce some of Spain's most robust and celebrated wines.\n\nWalk ancient Monastrell vines with an expert viticulturist, descend into cool atmospheric cellars, then take your seat for a sommelier-led tasting of Juan Gil's finest premium vintages. A spectacular multi-course lunch at the estate follows, each dish crafted from local ingredients and perfectly paired with a specific vintage.",
    featured: true
  },
  {
    id: 'ibiza-escape',
    name: 'Ibiza: Mediterranean Island Escape',
    tagline: 'Pristine beaches, bohemian markets',
    shortDesc: 'Cross the azure waters to the legendary island of Ibiza for a day of pristine beaches and vibrant culture.',
    duration: 'Full day · 12 hrs',
    price: '€350',
    priceNum: 350,
    maxGuests: 4,
    transport: 'Private Car & Ferry',
    category: 'Island & Coastal',
    image: 'https://images.unsplash.com/photo-1533676802871-eca1ae998cd5?auto=format&fit=crop&q=80&w=1200',
    highlights: ['Fast ferry crossing', 'Dalt Vila tour', 'Secluded cove', 'Beach club lunch', 'Hippy market'],
    fullDesc: "Discover the dual nature of Ibiza — a world-renowned haven for both tranquil bohemian retreats and vibrant coastal energy. This exclusive day trip takes you across the Mediterranean to explore hidden coves, historic Dalt Vila, and chic beach clubs.\n\nWe transfer you by Private Car to the port, then board a premium fast ferry. Explore the UNESCO-listed Dalt Vila, escape to a secluded cala for swimming, enjoy a luxurious beach club lunch with fresh seafood, and conclude with a visit to a famous hippy market.",
    featured: false
  },
  {
    id: 'altea-charm',
    name: 'Altea: The Dome of the Mediterranean',
    tagline: 'Whitewashed streets & artisan boutiques',
    shortDesc: "Wander through the whitewashed streets of Altea, the Costa Blanca's most picturesque coastal town.",
    duration: 'Half day · 5 hrs',
    price: '€145',
    priceNum: 145,
    maxGuests: 4,
    transport: 'Private Car',
    category: 'Culture & Sightseeing',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=1200',
    highlights: ['Old town walk', 'Artisan boutiques', 'Church dome views', 'Hillside lunch'],
    fullDesc: "Crowned by its iconic blue-and-white tiled church dome, Altea is a haven for artists and dreamers. This enchanting town offers a beautiful contrast to the bustling resorts nearby, preserving its traditional Spanish soul.\n\nArrive at the foot of Altea's old town and ascend through charming narrow streets lined with whitewashed houses and vibrant bougainvillea. Reach the Church of the Virgin of Consuelo for panoramic bay views, dine at a hillside restaurant, and stroll the pebble beach promenade.",
    featured: false
  },
  {
    id: 'dona-anna',
    name: 'Dona Anna: Coastal Elegance',
    tagline: 'Dramatic cliffs & crystalline waters',
    shortDesc: 'Experience the pristine beauty of the Dona Anna coastline with an exclusive, luxurious seaside retreat.',
    duration: 'Full day · 7 hrs',
    price: '€210',
    priceNum: 210,
    maxGuests: 4,
    transport: 'Private Car',
    category: 'Luxury & Coastal',
    image: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&q=80&w=1200',
    highlights: ['Cliff-top walk', 'Luxury beach loungers', 'Cliffside seafood lunch', 'VIP service'],
    fullDesc: "The Dona Anna coastal region is synonymous with dramatic cliffs, hidden grottos, and waters of impossible clarity. This tour is designed for those who appreciate the finer things, combining breathtaking scenery with unparalleled luxury.\n\nBegin with a chilled glass of cava upon arrival, then take a guided walk along dramatic cliff tops. Descend to a reserved luxury beach area, relax on private loungers, and indulge in a multi-course cliffside seafood feast paired with premium regional wines.",
    featured: false
  },
  {
    id: 'markedet-tour',
    name: 'Markedet: The Authentic Market Experience',
    tagline: "Insider access to Spain's beating culinary heart",
    shortDesc: 'Dive into the bustling local markets of the Costa Blanca, tasting fresh produce and regional culinary secrets.',
    duration: 'Half day · 4–5 hrs',
    price: '€135',
    priceNum: 135,
    maxGuests: 4,
    transport: 'Private Car',
    category: 'Culinary & Culture',
    image: 'https://images.unsplash.com/photo-1533900298318-6b8da08a523e?auto=format&fit=crop&q=80&w=1200',
    highlights: ['Guided market tour', 'Vendor interactions', 'Premium tastings', 'Authentic tapas lunch'],
    fullDesc: "To truly understand Spanish culture, one must visit its markets. The Mercado is the beating heart of the community — a vibrant, colorful spectacle where the freshest Mediterranean ingredients are proudly displayed.\n\nNavigate the bustling aisles with your guide, learn to select the best Jamón Ibérico, artisanal cheeses and fresh olives, sample premium cured meats and local wines from the stalls, then enjoy a traditional tapas lunch made from the very ingredients you just discovered.",
    featured: false
  },
  {
    id: 'guadalest-valley',
    name: 'Guadalest: The Mountain Fortress',
    tagline: 'Medieval history & emerald reservoir',
    shortDesc: 'Journey inland to the spectacular mountain village of Guadalest, famous for its castle and emerald reservoir.',
    duration: 'Half day · 5–6 hrs',
    price: '€155',
    priceNum: 155,
    maxGuests: 4,
    transport: 'Private Car',
    category: 'Nature & History',
    image: 'https://images.unsplash.com/photo-1559588500-1b211bf118c7?auto=format&fit=crop&q=80&w=1200',
    highlights: ['Castle of San José', 'Emerald reservoir views', 'Village exploration', 'Mountain lunch'],
    fullDesc: "Hidden in the rugged mountains of Alicante lies Guadalest, one of the most beautiful and historically significant villages in Spain. Perched on a limestone pinnacle, accessed only through a tunnel carved into the rock.\n\nClimb to the remains of the 11th-century Moorish castle for unparalleled panoramic views, gaze upon the stunning turquoise Embalse de Guadalest, explore quirky micro-museums and artisan shops, then conclude with a hearty mountain lunch of slow-cooked lamb and regional wines.",
    featured: false
  },
  {
    id: 'romantisk-tur',
    name: 'Romantic Escape: Evening Elegance',
    tagline: 'Candlelit dinners under Mediterranean stars',
    shortDesc: 'A meticulously crafted evening of romance, featuring secluded viewpoints, fine dining, and Mediterranean magic.',
    duration: 'Evening · 4–5 hrs',
    price: '€250',
    priceNum: 250,
    maxGuests: 4,
    transport: 'Private Car',
    category: 'Romance & Luxury',
    image: 'https://images.unsplash.com/photo-1517438322307-e67111335449?auto=format&fit=crop&q=80&w=1200',
    highlights: ['Secluded coastal viewpoint', 'Premium Cava & chocolates', 'Romantic promenade', 'Candlelit dinner'],
    fullDesc: "Celebrate love against the stunning backdrop of the Costa Blanca. Every detail of this exclusive evening tour is curated to provide a seamless, romantic journey under the Mediterranean stars.\n\nBegin at a hidden elevated viewpoint overlooking the sea with a chilled bottle of premium Cava and artisan chocolates. Stroll a quiet coastal promenade hand-in-hand, then spend the evening at a reservation at one of the region's most romantic restaurants — a multi-course tasting menu with wine pairings.",
    featured: false
  },
  {
    id: 'solnedgang-sunset',
    name: 'Sunset Magic: Coastal Twilight',
    tagline: 'Gold hour vistas with wine & tapas',
    shortDesc: 'Witness the spectacular Mediterranean sunset from exclusive vantage points with fine wine and local tapas.',
    duration: 'Evening · 3–4 hrs',
    price: '€165',
    priceNum: 165,
    maxGuests: 4,
    transport: 'Private Car',
    category: 'Nature & Relaxation',
    image: 'https://images.unsplash.com/photo-1515238152791-8216bfdf89a7?auto=format&fit=crop&q=80&w=1200',
    highlights: ['Scenic coastal drive', 'Exclusive sunset viewpoint', 'Premium wine', 'Gourmet tapas'],
    fullDesc: "There is a brief, magical window when the Costa Blanca's harsh daylight softens into brilliant hues of gold, pink, and violet. This sunset tour celebrates that golden hour from the most stunning, unobstructed clifftop viewpoints.\n\nBoard our Private Car as the late afternoon heat fades, enjoy the changing light along coastal cliffs, then arrive at a secluded elevated location just in time. Sip premium Spanish wines paired with gourmet tapas — artisanal cheeses, cured meats, fresh olives — as the sun dips below the horizon.",
    featured: false
  }
];

const LOGO = 'https://horizons-cdn.hostinger.com/fdaae8f6-c2cb-4e61-863e-e79e6b571eca/5e1471de21621c8a783339a25d92fc19.png';
const HERO_IMG = 'https://images.unsplash.com/photo-1602854127232-983309a47263?auto=format&fit=crop&q=85&w=1920';

const CATEGORIES = ['All', 'Culinary & Culture', 'Wine & Gastronomy', 'Adventure & Sports', 'Island & Coastal', 'Culture & Sightseeing', 'Luxury & Coastal', 'Nature & History', 'Romance & Luxury', 'Nature & Relaxation'];
